---
- name: Ensure open-iscsi package is installed
  package:
    name: "{{ iscsi_packages }}"
    state: present

- name: Set initiator name
  template:
    src: initiatorname.iscsi.j2
    dest: /etc/iscsi/initiatorname.iscsi
  notify: Restart iscsid

- name: Configure iscsid
  template:
    src: iscsid.conf.j2
    dest: /etc/iscsi/iscsid.conf
  notify: Restart iscsid

- name: Enable iscsid service
  service:
    name: iscsid
    enable: true

- name: config_targets | discovering targets
  open_iscsi:
    discover: "{{ item.discover }}"
    portal: "{{ item.portal }}"
  with_items: '{{ open_iscsi_targets }}'

- name: config_targets | configuring targets
  open_iscsi:
    discover: "{{ item.discover }}"
    login: "{{ item.login }}"
    portal: "{{ item.portal }}"
    target: "{{ item.target|default(omit) }}"
  with_items: '{{ open_iscsi_targets }}'
