---
- name: Configure iscsi-server
  hosts: iscsi-target
  become: true
  gather_facts: true
  vars:
    storage_partitions:
      - name: /dev/vdb
        number: 1
        flags:
          - lvm
        part_end: 1GB
    storage_volumegroups:
      - name: vg_iscsi
        devices:
          - /dev/vdb1
    storage_volumes:
      - name: vg_iscsi_lv_node1
        vg: vg_iscsi
        size: 100
      - name: vg_iscsi_lv_node2
        vg: vg_iscsi
        size: 100
      - name: vg_iscsi_lv_node3
        vg: vg_iscsi
        size: 100
      - name: vg_iscsi_lv_node4
        vg: vg_iscsi
        size: 100
    iscsi_targets:
      - name: iqn.2021-07.com.ricsanfre:iscsi-target
        disks:
          - name: lun_node1
            path: /dev/vg_iscsi/vg_iscsi_lv_node1
            type: block
            lunid: 0
          - name: lun_node2
            path: /dev/vg_iscsi/vg_iscsi_lv_node2
            type: block
            lunid: 1
          - name: lun_node3
            path: /dev/vg_iscsi/vg_iscsi_lv_node3
            type: block
            lunid: 2
          - name: lun_node4
            path: /dev/vg_iscsi/vg_iscsi_lv_node4
            type: block
            lunid: 3
        initiators:
          - name: iqn.2021-07.com.ricsanfre:iscsi-initiator
            authentication:
              userid: iqn.2021-07.com.ricsanfre:iscsi-initiator
              password: s1cret0
              userid_mutual: iqn.2021-07.com.ricsanfre:iscsi-target
              password_mutual: 0tr0s1cret0
            mapped_luns:
              - mapped_lunid: 0
                lunid: 0
              - mapped_lunid: 1
                lunid: 2
          - name: iqn.2021-07.com.ricsanfre:node2
            authentication:
              userid: node2
              password: passwd2
            mapped_luns:
              - mapped_lunid: 0
                lunid: 1
              - mapped_lunid: 1
                lunid: 3
                write_protect: 1
        portals:
          - ip: 192.168.0.11

  roles:
    - ricsanfre.storage
    - ricsanfre.iscsi_target

- name: Configure iscsi-client
  hosts: iscsi-initiator
  become: true
  gather_facts: true
  vars:
    open_iscsi_initiator_name: iqn.2021-07.com.ricsanfre:iscsi-initiator
    open_iscsi_authentication: true
    open_iscsi_auth_username: iqn.2021-07.com.ricsanfre:iscsi-initiator
    open_iscsi_auth_password: s1cret0
    open_iscsi_auth_username_in: iqn.2021-07.com.ricsanfre:iscsi-target
    open_iscsi_auth_password_in: 0tr0s1cret0
    open_iscsi_automatic_startup: true
    open_iscsi_targets:
      - name: iscsi-target
        discover: true
        auto_portal_startup: true
        auto_node_startup: true
        portal: 192.168.0.11
        target: iqn.2021-07.com.ricsanfre:iscsi-target
        login: true
  roles:
    - ricsanfre.iscsi_initiator
  tasks:
    - name: get iSCSI disks
      shell: "lsblk -S  | grep iscsi | cut -d' ' -f1"
      register: command
    - debug:
        var: command
    - name: set disks_variables
      set_fact:
        iscsi_disks: "{{ iscsi_disks|default([]) + [  '/dev/' + item  ] }}"
      with_items: "{{ command.stdout_lines }}"
    - name: set storage configuration
      set_fact:
        storage_volumegroups:
          - name: vg_iscsi
            devices: "{{ iscsi_disks }}"
        storage_volumes:
          - name: vg_iscsi_lv_node1
            vg: vg_iscsi
            size: 150
        storage_filesystems:
          - name: /dev/vg_iscsi/vg_iscsi_lv_node1
            filesystem: ext4
        storage_mounts:
          - name: /data
            src: /dev/vg_iscsi/vg_iscsi_lv_node1
            owner: root
            group: root
            mode: "0755"
            opts: _netdev
            boot: true
            dump: 0
            passno: 2
      when: iscsi_disks is defined
    - name: Include storage role
      include_role:
        name: ricsanfre.storage
      when: iscsi_disks is defined
