---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: iscsi-target
    box: generic/ubuntu2004
    cpu: 1
    memory: 1024
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.0.11
        auto_config: true
  - name: iscsi-initiator
    box: generic/ubuntu2004
    cpu: 1
    memory: 512
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.0.12
        auto_config: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
